include: package:flutter_lints/flutter.yaml

linter:
  rules:
    unawaited_futures: true
    prefer_double_quotes: true
    type_annotate_public_apis: true
analyzer:
  exclude:
    - "example/**"
    - "build/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
